### ISSUE TITLE
Email client fails with `SPAM not found`

### ISSUE THREAD

**Issue by nicopico-dev** [nicopico-dev/n2rss#137]
Retrieving emails failed with the following error:

```
jakarta.mail.FolderNotFoundException: SPAM not found
	at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:431)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1044)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:977)
	at fr.nicopico.n2rss.mail.client.JavaxEmailClient$checkEmails$1$1.invoke(JavaxEmailClient.kt:54)
	at fr.nicopico.n2rss.mail.client.JavaxEmailClient$checkEmails$1$1.invoke(JavaxEmailClient.kt:53)
	at fr.nicopico.n2rss.mail.client.JavaxEmailClient.doInFolder(JavaxEmailClient.kt:66)
	at fr.nicopico.n2rss.mail.client.JavaxEmailClient.checkEmails(JavaxEmailClient.kt:53)
	at fr.nicopico.n2rss.mail.EmailChecker.savePublicationsFromEmails(EmailChecker.kt:60)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.IllegalStateException: This operation is not allowed on a closed folder
		at com.sun.mail.imap.IMAPFolder.close(IMAPFolder.java:1486)
		at com.sun.mail.imap.IMAPFolder.close(IMAPFolder.java:1460)
		at jakarta.mail.Folder.close(Folder.java:645)
		at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:49)
		at fr.nicopico.n2rss.mail.client.JavaxEmailClient.doInFolder(JavaxEmailClient.kt:65)
		... 9 more
```

**Comment by nicopico-dev** [comment]
SPAM folder is named "Spam" (case-sensitive)
