### ISSUE TITLE
Kotlin Weekly #400 fails to parse

### ISSUE THREAD

**Issue by nicopico-dev** [nicopico-dev/n2rss#40]
Stacktrace
```
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 13:38:32 ERROR EmailChecker - Error processing email Kotlin Weekly #400
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: fr.nicopico.n2rss.mail.newsletter.NewsletterParsingException: Cannot find article description for article "Twitter" in Kotlin Weekly
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at fr.nicopico.n2rss.mail.newsletter.KotlinWeeklyNewsletterHandler.extractArticles(KotlinWeeklyNewsletterHandler.kt:67)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at fr.nicopico.n2rss.mail.newsletter.NewsletterHandler$DefaultImpls.process(NewsletterHandler.kt:35)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at fr.nicopico.n2rss.mail.newsletter.KotlinWeeklyNewsletterHandler.process(KotlinWeeklyNewsletterHandler.kt:31)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at fr.nicopico.n2rss.mail.EmailChecker.savePublicationsFromEmails(EmailChecker.kt:54)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at io.micrometer.observation.Observation.observe(Observation.java:499)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07/Apr/2024:13:38:32 +0200] [upstream] [106711] STDOUT: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Email: [Kotlin Weekly #400.eml.zip](https://github.com/nicopico-dev/n2rss/files/14897096/Kotlin.Weekly.400.eml.zip)

**Comment by nicopico-dev** [comment]
Probably caused by links to Twitter in the first article description
